### ISSUE TITLE
Feature request: allow impersonation with temporary context

### ISSUE THREAD

**Issue by jonmoter** [kubie-org/kubie#27]
Normally when I use kubectl to interact with shared/production clusters, I use credentials for a user with read-only permissions.  But the user has the ability to impersonate a user with admin-level permissions.  So if I need to make a change, I can run something like:
```
kubectl --as=admin --as-group=system:masters delete pod ${pod_name}
```

It's kindof like using `sudo` for executing commands with higher permissions.

It would be useful for me to be able to run something like this:
```
kubie ctx --as=admin --as-group=system:masters --as-reason="deleting stuck pod"
```

That would give me a shell where the temporary kubeconfig file would have:
```
users:
- name: user-as-admin
  user:
    # Normal credentials here, could be client certs, exec, whatever
    username: foo
    password: password123
    # Impersonation information below
    as: admin
    as-groups:
      - system:masters
    as-user-extra:
      reason:
        - deleting stuck pod
```

Then I could run a few commands with those credentials, and then exit out of the shell.

This would also be useful for CLI tools like `istioctl` that do not support passing `--as` as a command-line flag.
