### ISSUE TITLE
Error when not using inline certs/key

### ISSUE THREAD

**Issue by ghost** [kubie-org/kubie#33]
Looks like kubie doesn't handle copying the certs/keys to /tmp folder. The error below indicates that. Please see if you can fix this. Thanks. 

Great work btw.

```
[minikube|default] ➜  .kube git:(master) k get ns
Error in configuration:
* unable to read client-cert /tmp/minikube-client.crt for minikube due to open /tmp/minikube-client.crt: no such file or directory
* unable to read client-key /tmp/minikube-client.key for minikube due to open /tmp/minikube-client.key: no such file or directory
* unable to read certificate-authority /tmp/minikube-ca.crt for minikube due to open /tmp/minikube-ca.crt: no such file or directory

```

**Comment by sbstp** [comment]
Hey. I'm not sure this is a kubie issue. I need more details about your setup to know what's going on. Kubie doesn't touch any of the fields inside of a cluster or a user object, so it's likely that those paths were invalid in the first place and when kubie created the temporary context it copied the invalid information.

**Comment by ghost** [comment]
Below is what my kubeconfig looks like.
```
apiVersion: v1
kind: Config
current-context: minikube
clusters:
- cluster:
    certificate-authority: minikube-ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
users:
- name: minikube
  user:
    client-certificate: minikube-client.crt
    client-key: minikube-client.key
```
