### ISSUE TITLE
kubie ctx needs cluster admin role

### ISSUE THREAD

**Issue by nextsux** [kubie-org/kubie#45]
It's unable to enter context which is scopet only to one namespace:

```
kubie ctx gitlab@cluster
Error: Error calling kubectl: Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:klum:gitlab cannot list resource "namespaces" in API group "" at the cluster scope
```

where `gitlab@cluster` has role like this:
```
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
```
