### ISSUE TITLE
Feature requests: change kubectl binary version per cluster 

### ISSUE THREAD

**Issue by WMP** [kubie-org/kubie#76]
Hello i have few k8s clusters. Old clusters in version 1.13.12, and new in 1.16.13. When i execute command with kubectl version 1.16 `kubectl describe ingress` on cluster 1.13, i have error:
`Error from server (NotFound): the server could not find the requested resource`

So i must use older kubectl version, for example 1.14. I want to kubie set my kubectl binary per cluster. Kubie can read this kubectl binary version from cluster config file. 

This same problem i have with helm - on old clusters i use helm2, and on new i use helm3. 

My config proposal is to add aliases configuration:
```
apiVersion: v1
kind: Config
clusters:
  - cluster:
        api-version: v1
        certificate-authority-data: 
        server: 
        aliases: 
            kubectl: "~/bin/kubectl-1.14"
            helm:    "~/bin/helm2.14.1"
    name: 
contexts:
  - context:
        cluster: 
        user: 
        namespace: 
    name: 
current-context: 
users:
  - name: 
    user:
        client-certificate-data: 
        client-key-data: 
```
